kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-longhorn-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: jenkins
spec:
 replicas: 1
 selector:
   matchLabels:
     app: jenkins-app
 template:
  metadata:
   labels:
    app: jenkins-app
  spec:
   securityContext:
     fsGroup: 1000
   containers:
   - name: jenkins
     imagePullPolicy: IfNotPresent
     image: jenkins/jenkins:lts
     ports:
     - containerPort: 8080
     volumeMounts:
       - mountPath: /var/jenkins_home
         name: jenkins-home
   volumes:
     - name: jenkins-home
       persistentVolumeClaim:
         claimName: jenkins-longhorn-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: jenkins-app
  type: NodePort
